[tool.poetry]
name = "ayto-sat"
version = "0.1.0"
description = ""
authors = ["Alex Wong <awong593@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
